### ISSUE TITLE
Rate limiting & caching middleware.

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#125]
For the homepage, we need to have some caching middleware.

For some critical endpoints, we should have rate-limiting middleware (in-memory, no redis dependency).

Cfr. Bluewallet: https://github.com/BlueWallet/LndHub/blob/master/controllers/api.js#L138 (search for `postLimiter` for all the calls that use it).

**Comment by bumi** [comment]
In LnMe I had used [tollbooth v6](https://github.com/didip/tollbooth) https://github.com/bumi/lnme/blob/master/lnme.go#L31-L41 for rate limiting

**Comment by kiwiidb** [comment]
Well, there is also a native Echo rate-limit middleware: https://echo.labstack.com/middleware/rate-limiter/. Since we already use Echo, I would prefer that one.

**Comment by skosito** [comment]
@bumi @kiwiidb Thanks for suggestions, I checked out echo rate limiter because it fits nicely with echo, and also it is easy to set up, especially if we use default config, it is matter of specifying req per sec and which endpoints to protect - do you have specific req/s number and endpoints in mind already?

I tested it out with 1 req per sec and default config is IP based, returns 429 Too Many Requests with `rate limit exceeded`.

Regarding caching middleware for home endpoint, I found this one https://github.com/SporkHubr/echo-http-cache and also gave it a try, it is easy to set up and works fine on home endpoint with echo. It is probably better to use this one than to implement it from scratch. What do you think?

**Comment by kiwiidb** [comment]
We could have 1 request per 10 s for `/create` and `/pay` endpoints, the rest could be a bit more.
