### ISSUE TITLE
Add webhooks for invoice updates

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#153]
Webhooks are hard and complex to get right. E.g. we would need to have a system to reply failed webhooks etc.

There are external services that handle all this complexity for apps: e.g. https://www.svix.com

We could optionally add support for svix to send webhooks.

**Comment by kiwiidb** [comment]
I'm still hesitant to add dependencies on a single 3rd party service in the codebase. Wouldn't it be better to just add some basic configurable webooks without complexity? Similar to [fiatjaf's CLN plugin](https://github.com/fiatjaf/lightningd-webhook). No retry logic, and just a list of endpoints in the configuration. What do you think?

**Comment by kiwiidb** [comment]
Closed by #162

**Comment by tasn** [comment]
As @bumi said, doing webhooks reliably is a pain, that's why we created Svix in the first place. @kiwiidb, I understand your concern about adding 3rd party service dependencies, that's why Svix is OSS. Here's the repo: https://github.com/svix/svix-webhooks

Self-plug: I think having someone manage the infra for you so you don't have to worry for it is much nicer (that's the reason we exist as a company), but self-hosting the OSS project can also be fine. :)

**Comment by bumi** [comment]
@tasn thanks for your comment. I for sure like what you are doing with svix! Generally I also like outsourcing such non-core dev tasks. 
Also nice that you're open source.

**Comment by tasn** [comment]
Thanks @bumi. :)
