### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by kaikynetto** [getAlby/lndhub.go#238]
I can no longer create users in the api, what should I do?
![image](https://user-images.githubusercontent.com/109879025/196291528-d9a49201-114b-4698-99fb-69fac7c757bc.png)

**Comment by bumi** [comment]
Can you reach out via email (michael@getalby.com), what do you use the API for?

**Comment by kaikynetto** [comment]
Sorry to be annoying, how can I generate the admin token (oauth) you said

**Comment by kiwiidb** [comment]
Copying over from my response on mail:

Due to security considerations we decided to block user creation in the public LNDhub API. See https://github.com/getAlby/lndhub.go/pull/234.

We’ve been facing some large-scale DOS attacks, and locking this down is a first step in our defence in-depth against these. 

If you are looking to integrate Alby services, we prefer that you send us some information about your app and then you can use our OAuth API: https://guides.getalby.com/alby-wallet-api/reference/getting-started
