### ISSUE TITLE
Creating invoices with `amount: 0` is not possible

### ISSUE THREAD

**Issue by cnixbtc** [getAlby/lndhub.go#242]
It doesn't seem to be possible to create an invoice via the `POST /v2/invoices` endpoint with the following body:

```
{
  "amount": 0,
  "description: "whatever"
}
```

The error log on the server is:

```
{"level":"error","id":"(...)","time":"(...)","message":"Invalid addinvoice request body: Key: 'AddInvoiceRequestBody.Amount' Error:Field validation for 'Amount' failed on the 'required' tag"}
```

The [validation definition](https://github.com/getAlby/lndhub.go/blob/1efba841907bcca2cf63d6057b12078ff065309f/controllers_v2/invoice.ctrl.go#L128) is `"required,gte=0"`. It looks like `0` was originally meant to be a valid value (hence `gte=0`). However, after some quick googling, it seems like this is not compatible with `required` which, [according to the docs](https://pkg.go.dev/gopkg.in/go-playground/validator.v9#hdr-Required), "(...) ensures value is not zero".

I'm not a Go expert so I don't have a solution at hand but it seems like we'd need a different validation if we want to allow 0-value invoices (which would be a nice feature, imo). Not sure if I'll manage to open a PR myself anytime soon so I figured I'd just report it here. Let me know what you think!

**Comment by sangaman** [comment]
Zero value invoices seem desirable, I know there's a decent bit of real-world usage of them, and it would make sense to support. Especially if it just involves dropping that `required` tag. The other side of the coin would be having an ability to pay zero value invoices, which looks like is currently supported since you can specify an `amount` as well as an `invoice` when paying an invoice.
