### ISSUE TITLE
Failed outgoing payment appearing in transaction list

### ISSUE THREAD

**Issue by raucao** [getAlby/lndhub.go#381]
I just stumbled upon an entry for a failed payment in my outgoing transactions. The API included it in the list, with tx type `paid_invoice` and an empty `payment_preimage`. (Hotfix [here](https://gitea.kosmos.org/kosmos/akkounts/pulls/132/files) as an example.)

It was a fairly large payment that had failed 4 times or so before succeeding. But I only had one additional entry in the list for it, and it didn't affect my balance. Let me know if I can provide any more useful data, and/or if this is expected behavior or not.

**Comment by kiwiidb** [comment]
Hey @raucao , thanks for the report. According to the [relevant code](https://github.com/getAlby/lndhub.go/blob/main/lib/service/user.go#L176) this seems to be expected behaviour. However, I think you should have 1 entry per failed payment attempt (by this I mean per failed API call to `/payinvoice`). Was this in your Alby account or in a self-hosted LNDhub instance?

**Comment by raucao** [comment]
Thanks. This happened on a self-hosted instance.

> However, I think you should have 1 entry per failed payment attempt (by this I mean per failed API call to /payinvoice)

As stated above, there was more than 1 failed payment for this particular invoice. I also never saw failed txs in the list before, but then again, almost all payments just work these days, and we only switched from lndhub to lndhub.go last December. ;)

If it's intended behavior, then let's close this issue. I do find it a bit weird to have failed payments marked as "paid invoice" in a list, but cleaning up the legacy API is a whole new can of worms, and it's only tangentially related to my question.
